import { Transform } from 'stream';

const tokenMap: Record<string, string> = {
  'bg-[#0a0a0f]': 'bg-surface-primary',
  'bg-[#ffffff]': 'bg-white',
  'bg-[#000000]': 'bg-black',
  'text-[#6366f1]': 'text-accent',
  'text-[#9aa3b8]': 'text-secondary',
  'bg-[#22d3ee]': 'bg-accent-glow',
};

/**
 * Transforms and cleans AI-generated code by enforcing strict architectural rules,
 * swapping hardcoded colors for design tokens, and removing lazy placeholders.
 * 
 * @param content The raw string generated by AI
 * @returns The cleaned, "desloped" code string
 */
export function deslop(content: string): string {
    let cleaned = content;
    
    // 1. Auto-Fix Design Tokens
    for (const [slop, token] of Object.entries(tokenMap)) {
      cleaned = cleaned.replaceAll(slop, token);
    }

    // 2. Auto-Remove Lazy TODOs (JavaScript/TypeScript and HTML)
    cleaned = cleaned.replace(/\/\/\s*TODO:\s*implement later\s*\n?/gi, '');
    cleaned = cleaned.replace(/\/\/\s*TODO:[^\n]+\n?/gi, '');
    cleaned = cleaned.replace(/<!--\s*TODO:[^-]+-->\n?/gi, '');

    // 3. Remove stray console.logs (dangerous if AI leaves debugging slop)
    cleaned = cleaned.replace(/console\.log\([^)]+\);\n?/g, '');

    // 4. Auto-Fix basic Inline Styles to Tailwind
    const styleRegex = /style="margin-top:\s*20px;\s*letter-spacing:\s*1px;"/g;
    cleaned = cleaned.replace(styleRegex, 'class="mt-5 tracking-wide"');

    return cleaned;
}

/**
 * A Node.js Transform Stream for real-time AI code interception.
 * Use this to pipe AI responses directly before they hit the disk/user.
 */
export class DeslopStream extends Transform {
  constructor(options = {}) {
    super(options);
  }

  _transform(chunk: any, encoding: string, callback: Function) {
    const text = chunk.toString();
    const fixedText = deslop(text);
    this.push(fixedText);
    callback();
  }
}
