import { Transform } from 'stream';

const tokenMap: Record<string, string> = {
  'bg-[#0a0a0f]': 'bg-surface-primary',
  'text-[#6366f1]': 'text-accent',
  'text-[#9aa3b8]': 'text-secondary',
  'bg-[#22d3ee]': 'bg-accent-glow',
};

/**
 * Transforms and cleans AI-generated code by enforcing strict architectural rules,
 * swapping hardcoded colors for design tokens, and removing lazy placeholders.
 * 
 * @param content The raw string generated by AI
 * @returns The cleaned, "desloped" code string
 */
export function deslop(content: string): string {
    let cleaned = content;
    
    // 1. Auto-Fix Design Tokens
    for (const [slop, token] of Object.entries(tokenMap)) {
      cleaned = cleaned.replaceAll(slop, token);
    }

    // 2. Auto-Fix Inline Styles
    const styleRegex = /class="([^"]+)"\s*style="margin-top: 20px; letter-spacing: 1px;"/g;
    cleaned = cleaned.replace(styleRegex, 'class="$1 mt-5 tracking-wide"');

    // 3. Auto-Remove Lazy TODOs
    const todoRegex = /\s*<!-- \/\/ TODO:[^>]+-->\n?/g;
    cleaned = cleaned.replace(todoRegex, '');

    return cleaned;
}

/**
 * A Node.js Transform Stream for real-time AI code interception.
 * Use this to pipe AI responses directly before they hit the disk/user.
 */
export class DeslopStream extends Transform {
  constructor(options = {}) {
    super(options);
  }

  _transform(chunk: any, encoding: string, callback: Function) {
    const text = chunk.toString();
    const fixedText = deslop(text);
    this.push(fixedText);
    callback();
  }
}
